name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: make release
      run: make clean release
    - name: make debug
      run: make clean debug
    - name: make check
      run: make clean check
#    - name: make distcheck
#      run: make distcheck
    - uses: actions/upload-artifact@v2
      with:
        name: app.release
        path: app.release
    - uses: actions/upload-artifact@v2
      with:
        name: app.debug
        path: app.debug
