name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup packages
      run: sudo apt install clang llvm
#    - name: configure
#      run: ./configure
    - name: Build Release Version
      run: make clean release
    - name: Build Debug Version
      run: make clean debug
    - name: Build Tests
      run: make clean test
    - name: Run Tests
      run: make check
    - name: Show Code Coverage
      run: make coverage
#    - name: make distcheck
#      run: make distcheck
    - uses: actions/upload-artifact@v2
      with:
        name: app.release
        path: app.release
    - uses: actions/upload-artifact@v2
      with:
        name: app.debug
        path: app.debug
