name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # clone project and setup packages
    - uses: actions/checkout@v2
    - name: setup packages
      run: sudo apt install clang llvm
#    - name: configure
#      run: ./configure

    # build and upload release version
    - name: Build Release Version
      run: make clean release

    # build and update debug version
    - name: Build Debug Version
      run: make clean debug

    # run tests and check the code coverage 
    - name: Build Tests
      run: make clean test
    - name: Run Tests
      run: make check
    - name: Show Code Coverage
      run: make coverage
    
    # upload test and coverage files
    - uses: actions/upload-artifact@v2
      with:
        name: Testing and Code Coverage
        path: |
          app.coverage.html
          app.coverage.txt
          app.test
          
    # upload binaries
    - uses: actions/upload-artifact@v2
      with:
        name: Application Binaries
        path: |
          app.release
          app.debug

#    - name: make distcheck
#      run: make distcheck
